/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/objects/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create object upload session */
        post: operations["CreateObjectUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/objects/uploads/{uploadId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get object upload status */
        get: operations["GetObjectUploadById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/objects/uploads/{uploadId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete object upload */
        post: operations["CompleteObjectUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/objects/uploads/{uploadId}/download-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create short-lived download URL */
        post: operations["CreateObjectDownloadUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        ObjectPurpose: "problem.description" | "problem.testcase.input" | "problem.testcase.output" | "submission.source-code" | "judge.actual-output";
        /** @enum {string} */
        ObjectPolicy: "problem-public-read" | "problem-admin-only" | "submission-owner-private" | "judge-internal";
        /** @enum {string} */
        ObjectUploadStatus: "Initiated" | "Uploaded" | "Completed" | "Expired" | "Cancelled";
        CreateObjectUploadRequest: {
            purpose: components["schemas"]["ObjectPurpose"];
            policy: components["schemas"]["ObjectPolicy"];
            fileName: string;
            contentType: string;
            /** Format: int64 */
            contentLength: number;
        };
        UploadTransport: {
            /** @enum {string} */
            method: "PresignedPut" | "FormPost" | "ProxyUpload";
            /** Format: uri */
            uploadUrl?: string | null;
            headers?: {
                [key: string]: string;
            } | null;
            formFields?: {
                [key: string]: string;
            } | null;
            /** Format: date-time */
            expiresAt?: string | null;
        };
        CompleteObjectUploadRequest: {
            sha256?: string | null;
        };
        ObjectUploadDetail: {
            uploadId: string;
            purpose: components["schemas"]["ObjectPurpose"];
            policy: components["schemas"]["ObjectPolicy"];
            fileName: string;
            contentType: string;
            /** Format: int64 */
            contentLength: number;
            status: components["schemas"]["ObjectUploadStatus"];
            sha256?: string | null;
            objectKey?: string | null;
            upload?: components["schemas"]["UploadTransport"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            completedAt?: string | null;
            /** Format: date-time */
            expiresAt?: string | null;
        };
        CreateObjectDownloadUrlRequest: {
            /** @default 300 */
            ttlSeconds: number;
        };
        ObjectDownloadUrlResponse: {
            /** Format: uri */
            downloadUrl: string;
            /** Format: date-time */
            expiresAt: string;
        };
        ProblemDetails: {
            /** Format: uri */
            type?: string | null;
            title: string;
            status: number;
            detail?: string | null;
            instance?: string | null;
        };
    };
    responses: {
        /** @description The request payload or parameters are invalid. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Authentication is required. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description The current principal has no permission. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description The requested resource does not exist. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description The request conflicts with current state. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Unexpected server-side error. */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        /** @description Upload session identifier. */
        UploadId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    CreateObjectUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateObjectUploadRequest"];
            };
        };
        responses: {
            /** @description Upload session created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectUploadDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    GetObjectUploadById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Upload session identifier. */
                uploadId: components["parameters"]["UploadId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Upload session detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectUploadDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    CompleteObjectUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Upload session identifier. */
                uploadId: components["parameters"]["UploadId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteObjectUploadRequest"];
            };
        };
        responses: {
            /** @description Upload marked as completed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectUploadDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    CreateObjectDownloadUrl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Upload session identifier. */
                uploadId: components["parameters"]["UploadId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateObjectDownloadUrlRequest"];
            };
        };
        responses: {
            /** @description Download URL created. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectDownloadUrlResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
