/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/problems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List problems */
        get: operations["ListProblems"];
        put?: never;
        /** Create problem */
        post: operations["CreateProblem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/problems/{problemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get problem detail */
        get: operations["GetProblemById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update problem */
        patch: operations["UpdateProblem"];
        trace?: never;
    };
    "/api/v1/problems/{problemId}/test-cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List test cases for a problem */
        get: operations["ListProblemTestCases"];
        put?: never;
        /** Create test case for problem */
        post: operations["CreateProblemTestCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/problems/{problemId}/test-cases/{testCaseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete test case */
        delete: operations["DeleteProblemTestCase"];
        options?: never;
        head?: never;
        /** Update test case */
        patch: operations["UpdateProblemTestCase"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ProblemSummary: {
            /** Format: int64 */
            id: number;
            title: string;
            timeLimitMs: number;
            memoryLimitKb: number;
            /** Format: int64 */
            authorId: number;
            /** Format: date-time */
            createdAt: string;
        };
        ProblemDetail: components["schemas"]["ProblemSummary"] & {
            descriptionUploadId: string;
        };
        CreateProblemRequest: {
            title: string;
            descriptionUploadId: string;
            timeLimitMs: number;
            memoryLimitKb: number;
        };
        UpdateProblemRequest: {
            title?: string;
            descriptionUploadId?: string;
            timeLimitMs?: number;
            memoryLimitKb?: number;
        };
        TestCaseDetail: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            problemId: number;
            inputUploadId: string;
            expectedOutputUploadId: string;
            scoreWeight: number;
            isHidden: boolean;
        };
        CreateTestCaseRequest: {
            inputUploadId: string;
            expectedOutputUploadId: string;
            scoreWeight: number;
            isHidden: boolean;
        };
        UpdateTestCaseRequest: {
            inputUploadId?: string;
            expectedOutputUploadId?: string;
            scoreWeight?: number;
            isHidden?: boolean;
        };
        PageMeta: {
            page: number;
            pageSize: number;
            totalItems: number;
            totalPages: number;
        };
        PagedProblemSummaryResponse: {
            items: components["schemas"]["ProblemSummary"][];
            meta: components["schemas"]["PageMeta"];
        };
        TestCaseListResponse: {
            items: components["schemas"]["TestCaseDetail"][];
        };
        ProblemDetails: {
            /** Format: uri */
            type?: string | null;
            title: string;
            status: number;
            detail?: string | null;
            instance?: string | null;
        };
    };
    responses: {
        /** @description The request payload or parameters are invalid. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Authentication is required. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description The current principal has no permission. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description The requested resource does not exist. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description The request conflicts with current state. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Unexpected server-side error. */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        /** @description Problem identifier. */
        ProblemId: number;
        /** @description Test case identifier. */
        TestCaseId: number;
        /** @description 1-based page number. */
        Page: number;
        /** @description Page size. */
        PageSize: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ListProblems: {
        parameters: {
            query?: {
                /** @description 1-based page number. */
                page?: components["parameters"]["Page"];
                /** @description Page size. */
                pageSize?: components["parameters"]["PageSize"];
                /** @description Filter by problem author. */
                authorId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paged problem list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedProblemSummaryResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    CreateProblem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProblemRequest"];
            };
        };
        responses: {
            /** @description Problem created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    GetProblemById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Problem identifier. */
                problemId: components["parameters"]["ProblemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Problem detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    UpdateProblem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Problem identifier. */
                problemId: components["parameters"]["ProblemId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProblemRequest"];
            };
        };
        responses: {
            /** @description Problem updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    ListProblemTestCases: {
        parameters: {
            query?: {
                /** @description Include hidden cases in result, requires admin privileges. */
                includeHidden?: boolean;
            };
            header?: never;
            path: {
                /** @description Problem identifier. */
                problemId: components["parameters"]["ProblemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Test case list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCaseListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    CreateProblemTestCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Problem identifier. */
                problemId: components["parameters"]["ProblemId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTestCaseRequest"];
            };
        };
        responses: {
            /** @description Test case created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCaseDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    DeleteProblemTestCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Problem identifier. */
                problemId: components["parameters"]["ProblemId"];
                /** @description Test case identifier. */
                testCaseId: components["parameters"]["TestCaseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Test case deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    UpdateProblemTestCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Problem identifier. */
                problemId: components["parameters"]["ProblemId"];
                /** @description Test case identifier. */
                testCaseId: components["parameters"]["TestCaseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTestCaseRequest"];
            };
        };
        responses: {
            /** @description Test case updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCaseDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
