/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List submissions */
        get: operations["ListSubmissions"];
        put?: never;
        /** Create submission */
        post: operations["CreateSubmission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/submissions/{submissionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get submission detail */
        get: operations["GetSubmissionById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/submissions/{submissionId}/test-case-results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List test case results of submission */
        get: operations["ListSubmissionTestCaseResults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        JudgeStatus: "Pending" | "Running" | "Accepted" | "WrongAnswer" | "TimeLimitExceeded" | "MemoryLimitExceeded" | "RuntimeError" | "CompilationError" | "SystemError";
        SubmissionSummary: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            userId: number;
            /** Format: int64 */
            problemId: number;
            language: string;
            status: components["schemas"]["JudgeStatus"];
            maxTimeConsumedMs: number;
            maxMemoryConsumedKb: number;
            /** Format: date-time */
            submittedAt: string;
        };
        SubmissionDetail: components["schemas"]["SubmissionSummary"] & {
            codeUploadId: string;
        };
        CreateSubmissionRequest: {
            /** Format: int64 */
            problemId: number;
            /** @example cpp17 */
            language: string;
            codeUploadId: string;
        };
        SubmissionAcceptedResponse: {
            /** Format: int64 */
            submissionId: number;
            status: components["schemas"]["JudgeStatus"];
        };
        TestCaseResultDetail: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            submissionId: number;
            /** Format: int64 */
            testCaseId: number;
            status: components["schemas"]["JudgeStatus"];
            timeConsumedMs: number;
            memoryConsumedKb: number;
            actualOutputUploadId?: string | null;
            errorMessage?: string | null;
        };
        PageMeta: {
            page: number;
            pageSize: number;
            totalItems: number;
            totalPages: number;
        };
        PagedSubmissionSummaryResponse: {
            items: components["schemas"]["SubmissionSummary"][];
            meta: components["schemas"]["PageMeta"];
        };
        TestCaseResultListResponse: {
            items: components["schemas"]["TestCaseResultDetail"][];
        };
        ProblemDetails: {
            /** Format: uri */
            type?: string | null;
            title: string;
            status: number;
            detail?: string | null;
            instance?: string | null;
        };
    };
    responses: {
        /** @description The request payload or parameters are invalid. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Authentication is required. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description The current principal has no permission. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description The requested resource does not exist. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Business rule validation failed. */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Unexpected server-side error. */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        /** @description Submission identifier. */
        SubmissionId: number;
        /** @description 1-based page number. */
        Page: number;
        /** @description Page size. */
        PageSize: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ListSubmissions: {
        parameters: {
            query?: {
                /** @description 1-based page number. */
                page?: components["parameters"]["Page"];
                /** @description Page size. */
                pageSize?: components["parameters"]["PageSize"];
                /** @description Filter by submitter. */
                userId?: number;
                /** @description Filter by problem id. */
                problemId?: number;
                /** @description Filter by language key. */
                language?: string;
                /** @description Filter by judging status. */
                status?: components["schemas"]["JudgeStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paged submission list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedSubmissionSummaryResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    CreateSubmission: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSubmissionRequest"];
            };
        };
        responses: {
            /** @description Submission accepted for async judging. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionAcceptedResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["InternalServerError"];
        };
    };
    GetSubmissionById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Submission identifier. */
                submissionId: components["parameters"]["SubmissionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Submission detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    ListSubmissionTestCaseResults: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Submission identifier. */
                submissionId: components["parameters"]["SubmissionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Test case results for submission. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCaseResultListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
